### ISSUE TITLE
Reminder: Add back Merck ROR ID

### ISSUE THREAD

**Issue by jdblischak** [Merck/gsDesign2#556]
We can add back the Merck ROR ID once we can figure out how to submit to CRAN without `R CMD check` generating a NOTE

xref: https://github.com/Merck/gsDesign2/pull/544, https://github.com/Merck/gsDesign2/pull/555

**Comment by nanxstats** [comment]
I guess this has been fixed in upstream a few months ago: https://github.com/wch/r-source/commit/14f6248b2ea80dee26bbab31373deb8fc84a639a, perhaps somehow unfixed by more recent changes in `src/library/tools/R/check.R`.

Late last year, there was one time where using ORCID had similar issues for one of my packages, and I replied this in the incoming pretest email thread and it was agreed upon:

> Dear CRAN maintainers,
>
> I think this is a false positive.
>
> The 1 check note on pre-tests seems to be from the latest author parser changes in R source src/library/tools/R/check.R, which are still marked as FIXME.
>
> ...
>
> Thank you,
> -Nan

Take my experience with a grain of salt.

**Comment by LittleBeannie** [comment]
Thank you, John and Nan, for the thorough investigation and helpful discussion and summary.
For the upcoming release, I will remove the ROR for now, as we only have 3-4 days left before the deadline. I will add it back for the next release.

**Comment by jdblischak** [comment]
I checked the status of the NOTE from adding the ROR using `devtools::check_win_devel()`. It is still present. I had to change the maintainer of the package in order for the email to be sent to me, so I ran it twice: first without and then with the additional ROR comment. Only with the ROR did I get the NOTE about `Authors@R`

**Comment by nanxstats** [comment]
We released gsDesign 3.7.0 on CRAN earlier this week. On win-builder, it only generated a check note about ROR ID in r-oldrel (4.4), with nothing in r-release and r-devel, which means it will pass the formal submission pretesting (only runs on r-devel Debian and Windows). See the [DESCRIPTION](https://github.com/keaven/gsDesign/blob/master/DESCRIPTION) file.

Recently I did resolve a r-devel check note on `Authors@R` for my package: https://github.com/nanxstats/protr/pull/60 but not sure how relevant it is.

**Comment by jdblischak** [comment]
> We released gsDesign 3.7.0 on CRAN earlier this week. On win-builder, it only generated a check note about ROR ID in r-oldrel (4.4), with nothing in r-release and r-devel, which means it will pass the formal submission pretesting (only runs on r-devel Debian and Window

I believe that is because {gsDesign} 3.6.9 already had the ROR comment. That is what I have observed for other packages too. Once you get it on CRAN, then you will no longer get the NOTE about the difference, but you still get the note on the first submission.
